on: [push, pull_request]
name: Tests
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build    

      - name: Test
        run: go test . -timeout 5m -coverprofile=profile.cov

      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov